name: aroma_display
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_blue: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

    - family: KronaOne
      fonts:
        - asset: fonts/KronaOne-Regular.ttf

    - family: PaytoneOne
      fonts:
        - asset: fonts/PaytoneOne-Regular.ttf

    - family: RammettoOne
      fonts:
        - asset: fonts/RammettoOne-Regular.ttf